export type PlanId = 'free'|'pro'|'enterprise';
export type BillingInterval = 'month'|'year';
export interface Plan { id:PlanId; name:string; tagline:string; color:string; accentGlow:string; monthlyPrice:number; yearlyPrice:number; yearlyTotal:number; stripePriceIdMonthly:string; stripePriceIdYearly:string; features:{text:string;included:boolean}[]; limits:{threats:number|'unlimited';agents:number|'unlimited';logRetentionDays:number;teamMembers:number|'unlimited'}; popular?:boolean; cta:string; }
export const PLANS: Plan[] = [
  { id:'free', name:'Free', tagline:'For individuals getting started', color:'#00E6FF', accentGlow:'rgba(0,230,255,0.4)', monthlyPrice:0, yearlyPrice:0, yearlyTotal:0, stripePriceIdMonthly:'', stripePriceIdYearly:'', cta:'Get Started Free', popular:false, limits:{ threats:10, agents:1, logRetentionDays:7, teamMembers:1 }, features:[{text:'Up to 10 threat detections',included:true},{text:'1 neural agent',included:true},{text:'7-day log retention',included:true},{text:'Cookie Shield',included:true},{text:'Bot Monitor',included:false},{text:'Analytics & Reports',included:false},{text:'Team members',included:false},{text:'Priority support',included:false}] },
  { id:'pro', name:'Pro', tagline:'For professionals and growing teams', color:'#A45CFF', accentGlow:'rgba(164,92,255,0.5)', monthlyPrice:4900, yearlyPrice:3742, yearlyTotal:44900, stripePriceIdMonthly:process.env.NEXT_PUBLIC_STRIPE_PRO_MONTHLY??'', stripePriceIdYearly:process.env.NEXT_PUBLIC_STRIPE_PRO_YEARLY??'', cta:'Start Pro Trial', popular:true, limits:{ threats:'unlimited', agents:6, logRetentionDays:90, teamMembers:5 }, features:[{text:'Unlimited threat detections',included:true},{text:'All 6 neural agents',included:true},{text:'90-day log retention',included:true},{text:'Bot Monitor',included:true},{text:'Analytics & Reports',included:true},{text:'Up to 5 team members',included:true},{text:'Priority support',included:false}] },
  { id:'enterprise', name:'Enterprise', tagline:'For large teams and organisations', color:'#FF2E4C', accentGlow:'rgba(255,46,76,0.5)', monthlyPrice:9900, yearlyPrice:7492, yearlyTotal:89900, stripePriceIdMonthly:process.env.NEXT_PUBLIC_STRIPE_ENTERPRISE_MONTHLY??'', stripePriceIdYearly:process.env.NEXT_PUBLIC_STRIPE_ENTERPRISE_YEARLY??'', cta:'Start Enterprise Trial', popular:false, limits:{ threats:'unlimited', agents:'unlimited', logRetentionDays:365, teamMembers:'unlimited' }, features:[{text:'Unlimited threat detections',included:true},{text:'Unlimited neural agents',included:true},{text:'365-day log retention',included:true},{text:'Bot Monitor',included:true},{text:'Analytics & Reports',included:true},{text:'Unlimited team members',included:true},{text:'Priority support + SLA',included:true}] },
];
export function getPlan(id: PlanId): Plan { return PLANS.find(p=>p.id===id)??PLANS[0]; }
export function yearlySaving(plan: Plan): number { if(!plan.monthlyPrice) return 0; return Math.round(((plan.monthlyPrice*12-plan.yearlyTotal)/(plan.monthlyPrice*12))*100); }
