export interface DbThreat { id:string; name:string; source:string; severity:'critical'|'high'|'medium'|'low'; status:'active'|'investigating'|'mitigated'; description:string|null; created_at:string; updated_at:string; resolved_at:string|null; user_id:string|null; }
export interface DbLogEntry { id:string; level:'critical'|'warn'|'ok'|'info'; message:string; source:string|null; metadata:Record<string,unknown>; created_at:string; }
export interface DbAgent { id:string; name:string; role:'scanner'|'firewall'|'monitor'|'analyzer'; status:'active'|'idle'|'error'|'updating'; node:string; version:string; cpu_pct:number; mem_pct:number; tasks_today:number; uptime_hours:number; last_seen:string; created_at:string; updated_at:string; }
export interface DbBotEvent { id:string; actor:string; action_bold:string; action_light:string; status:'Blocked'|'Quarantined'|'Alert'|'Monitoring'; severity:'critical'|'high'|'medium'|'low'; origin:string|null; behavior:string|null; permissions:string|null; risk_pct:number; icon:string; created_at:string; }
export interface DbMetrics { id:string; threats_blocked:number; active_threats:number; nodes_monitored:number; threat_score:number; privacy_score:number; cookies_blocked:number; trackers_killed:number; recorded_at:string; }

export interface DbChildProfile { id: string; user_id: string; name: string; age: number; device: string | null; status: 'online' | 'offline' | 'restricted'; avatar_icon: string; screen_time_mins: number; screen_time_limit_mins: number; content_filter: 'G' | 'PG' | 'PG-13' | 'R'; alerts_today: number; created_at: string; }
export interface DbViewingActivity { id: string; child_id: string; child_name: string; platform: string; title: string; category: 'video' | 'social' | 'gaming' | 'web' | 'streaming'; rating: 'safe' | 'review' | 'flagged'; duration_mins: number; url: string | null; icon: string; created_at: string; }
export interface DbParentalAlert { id: string; child_id: string; child_name: string; title: string; message: string; severity: 'critical' | 'high' | 'medium' | 'low'; read: boolean; action_taken: 'blocked' | 'notified' | 'logged' | null; icon: string; created_at: string; }
