'use client';
import { motion } from 'framer-motion';
import Link from 'next/link';
import { useState } from 'react';
import { ContactModal } from '@/components/ui/ContactModal';
const PROTECTIONS=[{label:'Hidden Trackers',icon:'ti-radar',color:'#FF2E4C'},{label:'Rogue AI Bots',icon:'ti-robot',color:'#A45CFF'},{label:'Cookie Profiling',icon:'ti-cookie',color:'#FFB648'},{label:'Behavioral Fingerprinting',icon:'ti-fingerprint',color:'#00E6FF'},{label:'Suspicious Browser Activity',icon:'ti-browser',color:'#FF2E4C'},{label:'Unauthorized Data Access',icon:'ti-database-lock',color:'#00FF9C'},{label:'AI‑Driven Scraping Attempts',icon:'ti-spy',color:'#A45CFF'},{label:'Real-time threat detection',icon:'ti-shield-check',color:'#00E6FF'}];
const WHY=[{icon:'👁',title:'Clarity',color:'#00E6FF',desc:"See what's happening behind the screen — in real time, visually, without jargon."},{icon:'🧠',title:'Context',color:'#A45CFF',desc:'Understand what each threat means and why it matters to your digital life.'},{icon:'⚡',title:'Control',color:'#FF2E4C',desc:'Block, quarantine, or neutralize any threat instantly — with one click.'}];
const WHO=[{icon:'🎨',label:'Creators'},{icon:'💼',label:'Professionals'},{icon:'🎓',label:'Students'},{icon:'👨‍👩‍👧',label:'Families'},{icon:'🌐',label:'Everyday Users Who Deserve Transparency'},{icon:'🛡',label:'Anyone Who Refuses to Be Tracked Without Consent'}];
const FUTURE=['Privacy is visual','Security is intelligent','AI works for you, not against you','People understand their digital environment','Control belongs to the user, not the system'];
function SH({label}:{label:string}){return(<div className="flex items-center gap-3 mb-8"><span className="font-mono text-[10px] text-electricCyan/40">«</span><h2 className="font-rajdhani font-bold text-xl text-white tracking-[2px]">{label}</h2><div className="flex-1 h-px bg-white/5"/></div>);}
export default function AboutPage(){
  const [isContactOpen, setIsContactOpen] = useState(false);
  return(
    <div className="min-h-screen bg-deepVoid" style={{backgroundImage:'linear-gradient(rgba(0,230,255,0.018) 1px,transparent 1px),linear-gradient(90deg,rgba(0,230,255,0.018) 1px,transparent 1px)',backgroundSize:'32px 32px'}}>
      <nav className="sticky top-0 z-50 flex items-center justify-between px-6 md:px-8 h-[56px] bg-deepVoid/90 backdrop-blur-md border-b border-electricCyan/10">
        <Link href="/" className="flex items-center gap-3 font-rajdhani font-bold text-base tracking-[3px]">
          <img src="/guardian-ai-logo.jpeg" alt="Guardian AI Logo" className="w-10 h-10 rounded-md object-cover border border-electricCyan/50 shadow-[0_0_15px_rgba(0,230,255,0.35)] flex-shrink-0" />
          <span>4SIGHT <span className="text-electricCyan">GUARDIAN AI</span></span>
        </Link>
        <div className="hidden md:flex gap-6 font-mono text-[10px]">
          <Link href="/" className="text-white/35 hover:text-electricCyan uppercase">Home</Link>
          <span className="text-electricCyan uppercase">About</span>
          <a href="mailto:info@4sightgurdianai.com" className="text-white/35 hover:text-electricCyan uppercase">info@4sightgurdianai.com</a>
          <Link href="/pricing" className="text-white/35 hover:text-electricCyan uppercase">Pricing</Link>
          <button onClick={() => setIsContactOpen(true)} className="text-white/35 hover:text-electricCyan uppercase focus:outline-none">Contact</button>
        </div>
        <Link href="/signup"><motion.button whileHover={{scale:1.03,boxShadow:'0 0 16px rgba(0,230,255,0.3)'}} whileTap={{scale:0.97}} className="relative font-mono text-[9px] tracking-[1.5px] uppercase px-4 py-2 rounded-sm border border-electricCyan/40 text-electricCyan bg-electricCyan/8 overflow-hidden"><span className="absolute top-0 left-0 w-2.5 h-2.5 border-t border-l border-electricCyan/60"/><span className="absolute bottom-0 right-0 w-2.5 h-2.5 border-b border-r border-electricCyan/60"/>» Start Free</motion.button></Link>
      </nav>
      {/* HERO */}
      <section className="relative flex flex-col items-center justify-center text-center px-6 py-20 overflow-hidden">
        <div className="absolute inset-0 pointer-events-none" style={{background:'radial-gradient(ellipse 70% 60% at 50% 0%,rgba(164,92,255,0.12) 0%,transparent 65%)'}}/>
        <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:0.6}} className="flex items-center gap-3 mb-5 w-full max-w-2xl"><div className="flex-1 h-px bg-gradient-to-r from-transparent to-electricCyan/20"/><span className="font-mono text-[10px] tracking-[3px] text-electricCyan/45 uppercase whitespace-nowrap">// about 4sight guardian shield</span><div className="flex-1 h-px bg-gradient-to-l from-transparent to-electricCyan/20"/></motion.div>
        <motion.h1 initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:0.6,delay:0.1}} className="font-rajdhani font-bold text-4xl md:text-5xl tracking-wide leading-tight mb-5">Privacy Shouldn't Feel Like<br/><span style={{background:'linear-gradient(135deg,#00E6FF,#A45CFF)',WebkitBackgroundClip:'text',WebkitTextFillColor:'transparent',backgroundClip:'text'}}>Paperwork</span>. It Should Feel Like <span className="text-neoCrimson">Power</span>.</motion.h1>
        <motion.p initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{duration:0.6,delay:0.2}} className="font-mono text-[11px] text-white/35 max-w-xl leading-[1.9]">4Sight Guardian Shield was created with one mission: give people the power to see the invisible forces tracking them online — and stop them.</motion.p>
      </section>
      <div className="h-px bg-gradient-to-r from-transparent via-white/8 to-transparent mx-8"/>
      {/* MISSION */}
      <section className="max-w-4xl mx-auto px-6 py-14"><SH label="🌌 Our Mission"/><motion.div initial={{opacity:0,y:10}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="relative p-8 rounded-sm border border-plasmaViolet/25 bg-[rgba(10,8,14,0.8)] overflow-hidden"><span className="absolute top-0 left-0 w-4 h-4 border-t-2 border-l-2 border-plasmaViolet/60"/><span className="absolute bottom-0 right-0 w-4 h-4 border-b-2 border-r-2 border-plasmaViolet/60"/><div className="absolute inset-0 opacity-[0.035] pointer-events-none" style={{backgroundImage:'linear-gradient(rgba(0,230,255,1) 1px,transparent 1px),linear-gradient(90deg,rgba(0,230,255,1) 1px,transparent 1px)',backgroundSize:'24px 24px'}}/><div className="absolute top-0 left-0 right-0 h-40 pointer-events-none" style={{background:'radial-gradient(ellipse 80% 120% at 50% 0%,rgba(164,92,255,0.1),transparent 70%)'}}/><p className="font-mono text-[11px] text-white/55 leading-[2] relative z-10">Every second, hidden trackers, AI bots, and data‑harvesting scripts move through the web like shadows. Most privacy tools bury the truth behind menus, jargon, and settings no one has time to understand.<br/><br/><span className="text-electricCyan">4Sight flips that dynamic.</span><br/><br/>It turns privacy into something <span className="text-electricCyan">visual</span>, <span className="text-plasmaViolet">intelligent</span>, and <span className="text-emeraldPulse">alive</span> — a real‑time shield that watches your digital surroundings the way a hero watches a battlefield.</p></motion.div></section>
      <div className="h-px bg-gradient-to-r from-transparent via-white/8 to-transparent mx-8"/>
      {/* WHY */}
      <section className="max-w-4xl mx-auto px-6 py-14"><SH label="⚡ Why We Exist"/><p className="font-mono text-[11px] text-white/35 mb-6 leading-[1.9]">The modern internet is built on surveillance. Your clicks, your patterns, your identity — all quietly collected.</p><div className="grid grid-cols-1 md:grid-cols-3 gap-3 mb-6">{WHY.map(w=><motion.div key={w.title} initial={{opacity:0,y:10}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="relative p-5 rounded-sm border overflow-hidden hover:-translate-y-1 transition-all" style={{borderColor:`${w.color}28`,background:`${w.color}06`}}><span className="absolute top-0 left-0 w-3 h-3 border-t-2 border-l-2" style={{borderColor:w.color}}/><div className="text-3xl mb-3">{w.icon}</div><h3 className="font-rajdhani font-bold text-lg mb-2" style={{color:w.color}}>{w.title}</h3><p className="font-mono text-[10px] text-white/40 leading-[1.8]">{w.desc}</p></motion.div>)}</div><p className="text-center font-mono text-[11px] text-white/45">We believe privacy shouldn't feel like paperwork. <span className="text-electricCyan">It should feel like power.</span></p></section>
      <div className="h-px bg-gradient-to-r from-transparent via-white/8 to-transparent mx-8"/>
      {/* PROTECTIONS */}
      <section className="max-w-4xl mx-auto px-6 py-14"><SH label="🛡️ What 4Sight Protects You From"/><div className="grid grid-cols-1 md:grid-cols-2 gap-2.5 mb-5">{PROTECTIONS.map(p=><motion.div key={p.label} initial={{opacity:0,y:10}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="relative flex items-center gap-3 px-4 py-3.5 rounded-sm border border-white/7 bg-white/[0.02] overflow-hidden hover:border-white/15 transition-all"><div className="absolute left-0 top-0 bottom-0 w-[3px]" style={{background:p.color}}/><div className="w-9 h-9 rounded-sm flex items-center justify-center border flex-shrink-0" style={{color:p.color,borderColor:`${p.color}35`,background:`${p.color}0c`}}><i className={`ti ${p.icon}`} style={{fontSize:18}}/></div><span className="font-mono text-[11px] text-white/65">{p.label}</span></motion.div>)}</div><div className="px-4 py-4 rounded-sm border border-electricCyan/15 bg-electricCyan/4 font-mono text-[10px] text-white/40 leading-[1.9]">Instead of leaving you blind, 4Sight gives you a <span className="text-electricCyan">living HUD</span> that reacts, pulses, and adapts to your digital environment in real time.</div></section>
      <div className="h-px bg-gradient-to-r from-transparent via-white/8 to-transparent mx-8"/>
      {/* PHILOSOPHY */}
      <section className="max-w-4xl mx-auto px-6 py-14"><SH label="🔮 Our Philosophy"/><motion.div initial={{opacity:0,y:10}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="relative p-10 rounded-sm border border-electricCyan/18 bg-[rgba(10,8,14,0.8)] text-center overflow-hidden"><span className="absolute top-0 left-0 w-4 h-4 border-t-2 border-l-2 border-electricCyan/40"/><span className="absolute bottom-0 right-0 w-4 h-4 border-b-2 border-r-2 border-electricCyan/40"/><p className="font-rajdhani font-bold text-2xl md:text-3xl text-white mb-4 leading-snug">"If you can <span className="text-electricCyan">see the threat</span>, you can control it.<br/>If you can control it, you can <span className="text-plasmaViolet">own your digital life</span>."</p><p className="font-mono text-[10px] text-white/35 leading-[1.9] max-w-lg mx-auto">We blend AI threat detection, anime‑futurist design, and real‑time behavioral analysis to create a privacy experience that feels like stepping into your own command center.<br/><br/>This isn't just software. It's your <span className="text-electricCyan">AI‑powered digital guardian</span> — always watching the watchers.</p></motion.div></section>
      <div className="h-px bg-gradient-to-r from-transparent via-white/8 to-transparent mx-8"/>
      {/* WHO */}
      <section className="max-w-4xl mx-auto px-6 py-14"><SH label="🚀 Who We Build For"/><div className="grid grid-cols-1 md:grid-cols-3 gap-2.5 mb-6">{WHO.map(w=><motion.div key={w.label} initial={{opacity:0,y:10}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="flex items-center gap-3 px-4 py-3.5 rounded-sm border border-neoCrimson/15 bg-neoCrimson/4 hover:border-neoCrimson/35 hover:bg-neoCrimson/8 transition-all"><span className="text-xl flex-shrink-0">{w.icon}</span><span className="font-mono text-[10px] text-white/60">{w.label}</span></motion.div>)}</div><p className="text-center font-mono text-[13px] text-neoCrimson tracking-[1px]">If you live online, 4Sight protects you.</p></section>
      <div className="h-px bg-gradient-to-r from-transparent via-white/8 to-transparent mx-8"/>
      {/* FUTURE */}
      <section className="max-w-4xl mx-auto px-6 py-14"><SH label="🌐 The Future We're Building"/><p className="font-mono text-[11px] text-white/30 mb-5">A world where:</p><div className="flex flex-col gap-2">{FUTURE.map(f=><motion.div key={f} initial={{opacity:0,x:-10}} whileInView={{opacity:1,x:0}} viewport={{once:true}} className="flex items-center gap-4 px-5 py-3.5 rounded-sm border border-emeraldPulse/12 bg-emeraldPulse/3 hover:border-emeraldPulse/30 hover:bg-emeraldPulse/7 hover:translate-x-1 transition-all"><div className="w-2 h-2 rounded-full bg-emeraldPulse flex-shrink-0" style={{boxShadow:'0 0 8px #00FF9C'}}/><span className="font-mono text-[11px] text-white/65">{f}</span></motion.div>)}</div><p className="text-center font-mono text-[12px] text-white/45 mt-6">4Sight Guardian Shield is the <span className="text-emeraldPulse">first step</span> toward that future.</p></section>
      {/* CTA */}
      <section className="relative text-center px-6 py-20 border-t border-white/5 overflow-hidden"><div className="absolute inset-0 pointer-events-none" style={{background:'radial-gradient(ellipse 60% 80% at 50% 50%,rgba(164,92,255,0.07) 0%,transparent 65%)'}}/><h2 className="font-rajdhani font-bold text-3xl md:text-4xl text-white mb-3 relative z-10">Ready to Own Your<br/><span className="text-plasmaViolet">Digital Life?</span></h2><p className="font-mono text-[11px] text-white/30 mb-8 relative z-10">Join thousands of users who chose to see the invisible — and stop it.</p><div className="flex items-center justify-center gap-3 relative z-10 flex-wrap"><Link href="/signup"><motion.button whileHover={{scale:1.03,boxShadow:'0 0 24px rgba(164,92,255,0.4)'}} whileTap={{scale:0.97}} className="relative px-8 py-3.5 rounded-sm border border-plasmaViolet/50 text-plasmaViolet bg-plasmaViolet/12 font-mono text-[11px] tracking-[1.5px] uppercase overflow-hidden"><span className="absolute top-0 left-0 w-2.5 h-2.5 border-t border-l border-plasmaViolet/60"/><span className="absolute bottom-0 right-0 w-2.5 h-2.5 border-b border-r border-plasmaViolet/60"/>» Start Free Trial</motion.button></Link><Link href="/login"><motion.button whileHover={{scale:1.03}} whileTap={{scale:0.97}} className="relative px-8 py-3.5 rounded-sm border border-electricCyan/30 text-electricCyan bg-electricCyan/6 font-mono text-[11px] tracking-[1.5px] uppercase overflow-hidden"><span className="absolute top-0 left-0 w-2.5 h-2.5 border-t border-l border-electricCyan/50"/><span className="absolute bottom-0 right-0 w-2.5 h-2.5 border-b border-r border-electricCyan/50"/>Log In</motion.button></Link></div></section>
      <footer className="flex items-center justify-between px-6 md:px-8 py-6 border-t border-white/5 flex-wrap gap-4">
        <div className="flex items-center gap-3 font-rajdhani font-bold text-sm tracking-[2px]">
          <img src="/guardian-ai-logo.jpeg" alt="Guardian AI Logo" className="w-7 h-7 rounded-md object-cover border border-electricCyan/40 shadow-[0_0_10px_rgba(0,230,255,0.25)] flex-shrink-0" />
          <span>4SIGHT <span className="text-electricCyan">GUARDIAN AI</span></span>
        </div>
        <div className="flex gap-5 font-mono text-[9px] items-center">
          {[['Home','/'],['About','/about'],['Pricing','/pricing'],['Contact','contact']].map(([l,h])=>
            h === 'contact' ? (
              <button key={l} onClick={() => setIsContactOpen(true)} className="text-white/25 hover:text-electricCyan transition-colors uppercase focus:outline-none">{l}</button>
            ) : (
              <Link key={l} href={h} className="text-white/25 hover:text-electricCyan transition-colors uppercase">{l}</Link>
            )
          )}
          <a href="mailto:info@4sightgurdianai.com" className="text-white/25 hover:text-electricCyan transition-colors uppercase ml-2 border-l border-white/10 pl-4">info@4sightgurdianai.com</a>
        </div>
        <div className="flex items-center gap-2"><motion.span animate={{opacity:[1,0.2,1]}} transition={{duration:2,repeat:Infinity}} className="w-1.5 h-1.5 rounded-full bg-electricCyan"/><span className="font-mono text-[9px] text-white/20 italic">Analyzing AI threats in real time...</span></div>
      </footer>
      <ContactModal isOpen={isContactOpen} onClose={() => setIsContactOpen(false)} />
    </div>
  );
}
